server:
  port: 7900
  
spring:
  application:
    name: jt-sso-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jtdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 
  redis: 
    host: 192.168.80.134
    port: 7000
            
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka

mybatis:
  mapUnderscoreToCamelCase: true
  typeAliasesPackage: com.jt.sso.pojo
  mapperLocations: classpath:mybatis/mappers/*.xml
  
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

ribbon:
  eureka:
    enabled: true
    
logging:
  level: 
    com.jt.sso.mapper: debug

