/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2018-12-24 13:01:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class exception_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\"\r\n");
      out.write(" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"../css/header.css\" rel=\"Stylesheet\"/>\r\n");
      out.write("    <link href=\"../css/footer.css\" rel=\"Stylesheet\"/>\r\n");
      out.write("    <link href=\"../css/404.css\" rel=\"Stylesheet\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<!-- 页面顶部-->\r\n");
      out.write("<header id=\"top\">\r\n");
      out.write("    <div id=\"logo\" class=\"lf\">\r\n");
      out.write("        <img class=\"animated jello\" src=\"../images/header/logo.png\" alt=\"logo\"/>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"top_input\" class=\"lf\">\r\n");
      out.write("        <input id=\"input\" type=\"text\" placeholder=\"请输入您要搜索的内容\"/>\r\n");
      out.write("        <div class=\"seek\" tabindex=\"-1\">\r\n");
      out.write("            <div class=\"actived\" ><span>分类搜索</span> <img src=\"../images/header/header_normal.png\" alt=\"\"/></div>\r\n");
      out.write("            <div class=\"seek_content\" >\r\n");
      out.write("                <div id=\"shcy\" >生活餐饮</div>\r\n");
      out.write("                <div id=\"xxyp\" >学习用品</div>\r\n");
      out.write("                <div id=\"srdz\" >私人订制</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <a href=\"\" class=\"rt\"><img id=\"search\" src=\"../images/header/search.png\" alt=\"搜索\"/></a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"rt\">\r\n");
      out.write("        <ul class=\"lf\">\r\n");
      out.write("            <li><a href=\"myCollect.html\" title=\"我的收藏\"><img class=\"care\" src=\"../images/header/care.png\" alt=\"\"/></a><b>|</b></li>\r\n");
      out.write("            <li><a href=\"myOrder.html\" title=\"我的订单\"><img class=\"order\" src=\"../images/header/order.png\" alt=\"\"/></a><b>|</b></li>\r\n");
      out.write("            <li><a href=\"cart.html\" title=\"我的购物车\"><img class=\"shopcar\" src=\"../images/header/shop_car.png\" alt=\"\"/></a><b>|</b></li>\r\n");
      out.write("            <li><a href=\"lookforward.html\">帮助</a><b>|</b></li>\r\n");
      out.write("            <li><a href=\"login.html\">登录</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("<!-- nav主导航-->\r\n");
      out.write("<nav id=\"nav\">\r\n");
      out.write("    <ul>\r\n");
      out.write("        <li><a href=\"index.html\" class=\"active\">首页</a></li>\r\n");
      out.write("        <li><a href=\"item_food.html\">生活餐饮</a></li>\r\n");
      out.write("        <li><a href=\"itemCat.html\">学习用品</a></li>\r\n");
      out.write("        <li><a href=\"lookforward.html\">私人定制</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("</nav>\r\n");
      out.write("<!--500-->\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write("    <div class=\"rightsidebar_box rt\" >\r\n");
      out.write("        <div class=\"sys_err\">\r\n");
      out.write("            <img src=\"../images/500/500_img1.png\" alt=\"\"/>\r\n");
      out.write("            <p>\r\n");
      out.write("                <img src=\"../images/500/500_img2.png\" alt=\"\"/>服务器发生了错误！");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("            </p>\r\n");
      out.write("            <span>快去看看别的吧！<b><a href=\"#\">回首页&gt;&gt;</a></b></span>\r\n");
      out.write("            <br/>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!--为你推荐-->\r\n");
      out.write("<div id=\"recommended\">\r\n");
      out.write("    <p>为你推荐<span>大家都在看</span></p>\r\n");
      out.write("    <div id=\"demo\" style=\"width:1000px;overflow:hidden;\"><!-- 外面的大框 -->\r\n");
      out.write("        <div id=\"indemo\" style=\"float: left;width: 200%;\"><!-- 宽度特别大 -->\r\n");
      out.write("            <div id=\"demo1\" style=\"float:left\"><!-- 第一个宽度显示 -->\r\n");
      out.write("                <div class=\"detail_1 lf\">\r\n");
      out.write("                    <div class=\"detail_img1\">\r\n");
      out.write("                        <img src=\"../images/recommend/recommend_img1.png\" border=\"0\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p>ThinkPad New S2 (20GUA00QCD)13.3英寸超霸笔记本电脑</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"detail_1 lf\">\r\n");
      out.write("                    <div class=\"detail_img1\">\r\n");
      out.write("                        <img src=\"../images/recommend/recommend_img2.png\" border=\"0\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p>戴尔 DELL燃7000 R1605S 超霸笔记本电脑</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"detail_1 lf\">\r\n");
      out.write("                    <div class=\"detail_img1\">\r\n");
      out.write("                        <img src=\"../images/recommend/recommend_img3.png\" border=\"0\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p>戴尔(DELL)魔方15MF Pro-R2505TSS灵越超霸笔记本电脑</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"detail_1 lf\">\r\n");
      out.write("                    <div class=\"detail_img1\">\r\n");
      out.write("                        <img src=\"../images/recommend/recommend_img4.png\" border=\"0\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p>联想(Lenovo) YOGA900 (YOGA4 PRO)多彩版超霸笔记本电脑</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--</div>-->\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"demo2\" style=\"float:left\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- 宽度超大 -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- 外面大框 -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 品质保障，私人定制等-->\r\n");
      out.write("<div id=\"foot_box\">\r\n");
      out.write("    <div class=\"icon1 lf\">\r\n");
      out.write("        <img src=\"../images/footer/icon1.png\" alt=\"\"/>\r\n");
      out.write("\r\n");
      out.write("        <h3>品质保障</h3>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"icon2 lf\">\r\n");
      out.write("        <img src=\"../images/footer/icon2.png\" alt=\"\"/>\r\n");
      out.write("\r\n");
      out.write("        <h3>私人定制</h3>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"icon3 lf\">\r\n");
      out.write("        <img src=\"../images/footer/icon3.png\" alt=\"\"/>\r\n");
      out.write("\r\n");
      out.write("        <h3>学员特供</h3>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"icon4 lf\">\r\n");
      out.write("        <img src=\"../images/footer/icon4.png\" alt=\"\"/>\r\n");
      out.write("\r\n");
      out.write("        <h3>专属特权</h3>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 页面底部-->\r\n");
      out.write("<div class=\"foot_bj\">\r\n");
      out.write("    <div id=\"foot\">\r\n");
      out.write("        <div class=\"lf\">\r\n");
      out.write("            <p class=\"footer1\"><img src=\"../images/footer/logo.png\" alt=\"\" class=\" footLogo\"/></p>\r\n");
      out.write("            <p class=\"footer2\"><img src=\"../images/footer/footerFont.png\" alt=\"\"/></p>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"foot_left lf\" >\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\"><h3>买家帮助</h3></a></li>\r\n");
      out.write("                <li><a href=\"#\">新手指南</a></li>\r\n");
      out.write("                <li><a href=\"#\">服务保障</a></li>\r\n");
      out.write("                <li><a href=\"#\">常见问题</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\"><h3>商家帮助</h3></a></li>\r\n");
      out.write("                <li><a href=\"#\">商家入驻</a></li>\r\n");
      out.write("                <li><a href=\"#\">商家后台</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\"><h3>关于我们</h3></a></li>\r\n");
      out.write("                <li><a href=\"#\">关于拼多</a></li>\r\n");
      out.write("                <li><a href=\"#\">联系我们</a></li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <img src=\"../images/footer/wechat.png\" alt=\"\"/>\r\n");
      out.write("                    <img src=\"../images/footer/sinablog.png\" alt=\"\"/>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"service\">\r\n");
      out.write("            <p>拼多商城客户端</p>\r\n");
      out.write("            <img src=\"../images/footer/ios.png\" class=\"lf\">\r\n");
      out.write("            <img src=\"../images/footer/android.png\" alt=\"\" class=\"lf\"/>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"download\">\r\n");
      out.write("            <img src=\"../images/footer/erweima.png\">\r\n");
      out.write("        </div>\r\n");
      out.write("\t\t<!-- 页面底部-备案号 #footer -->\r\n");
      out.write("        <div class=\"record\">\r\n");
      out.write("            &copy;2017 拼多集团有限公司 版权所有 京ICP证xxxxxxxxxxx\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"../js/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("<script src=\"../js/index.js\"></script>\r\n");
      out.write("<!--图片轮播悬停进入详情页效果-->\r\n");
      out.write("<script>\r\n");
      out.write("    var speed = 20;\r\n");
      out.write("    var tab = document.getElementById(\"demo\");\r\n");
      out.write("    var tab1 = document.getElementById(\"demo1\");\r\n");
      out.write("    var tab2 = document.getElementById(\"demo2\");\r\n");
      out.write("    tab2.innerHTML = tab1.innerHTML;\r\n");
      out.write("    function Marquee() {\r\n");
      out.write("        if (tab2.offsetWidth - tab.scrollLeft <= 0)\r\n");
      out.write("            tab.scrollLeft -= tab1.offsetWidth\r\n");
      out.write("        else {\r\n");
      out.write("            tab.scrollLeft++;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    var MyMar = setInterval(Marquee, speed);\r\n");
      out.write("    tab.onmouseover = function () {\r\n");
      out.write("        clearInterval(MyMar)\r\n");
      out.write("    };\r\n");
      out.write("    tab.onmouseout = function () {\r\n");
      out.write("        MyMar = setInterval(Marquee, speed)\r\n");
      out.write("    };\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
